site_name: Open Source Policy Documentation
site_description: A comprehensive documentation site for public policies on open source software, organized by policy type.
site_url: https://EL-BID.github.io/OSS_policies
repo_url: https://github.com/EL-BID/OSS_policies
repo_name: EL-BID/OSS_policies 

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy

plugins:
  - search
  - i18n:
      docs_structure: folder
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: es
          name: Español
          build: true
          nav_translations:
            Home: Inicio
            Policies: Políticas
            Contribution: Contribución
            Public Release of State-Owned Software: Liberación Pública de Software Propiedad del Estado
            Prioritize Open Source in Procurement: Priorización de Código Abierto en Adquisiciones
            Reuse and Transfer of Government Software: Reutilización y Transferencia de Software Gubernamental
            Open Source Security Measures: Medidas de Seguridad para el Código Abierto
            Open Source Sharing Platforms: Plataformas para Compartir Código Abierto
            Mandatory Contribution Back to OSS: Contribución Obligatoria a Proyectos de Código Abierto
            Open Standards Requirement: Requisito de Estándares Abiertos
            Licensing Frameworks and Guidelines: Marcos y Directrices de Licenciamiento
            OSS Training Programs: Programas de Capacitación en Código Abierto
            OSS in Strategic Planning Documents: Código Abierto en Documentos de Planificación Estratégica
            Complete Country Overview: Resumen Completo por País
        - locale: pt
          name: Português
          build: true
          nav_translations:
            Home: Início
            Policies: Políticas
            Contribution: Contribuição
            Public Release of State-Owned Software: Liberação Pública de Software de Propriedade do Estado
            Prioritize Open Source in Procurement: Priorização de Código Aberto em Aquisições
            Reuse and Transfer of Government Software: Reutilização e Transferência de Software Governamental
            Open Source Security Measures: Medidas de Segurança para Código Aberto
            Open Source Sharing Platforms: Plataformas para Compartilhamento de Código Aberto
            Mandatory Contribution Back to OSS: Contribuição Obrigatória de Volta para Projetos de Código Aberto
            Open Standards Requirement: Requisito de Padrões Abertos
            Licensing Frameworks and Guidelines: Estruturas e Diretrizes de Licenciamento
            OSS Training Programs: Programas de Capacitação em Código Aberto
            OSS in Strategic Planning Documents: Código Aberto em Documentos de Planejamento Estratégico
            Complete Country Overview: Visão Geral Completa por País

nav:
  - Home: index.md
  - Policies:
    - Public Release of State-Owned Software: policies/public-release-state-owned.md
    - Prioritize Open Source in Procurement: policies/prioritize-open-source-procurement.md
    - Reuse and Transfer of Government Software: policies/reuse-transfer-government-software.md
    - Open Source Security Measures: policies/open-source-security-measures.md
    - Open Source Sharing Platforms: policies/open-source-sharing-platforms.md
    - Mandatory Contribution Back to OSS: policies/mandatory-contribution-back-oss.md
    - Open Standards Requirement: policies/open-standards-requirement.md
    - Licensing Frameworks and Guidelines: policies/licensing-frameworks-guidelines.md
    - OSS Training Programs: policies/oss-training-programs.md
    - OSS in Strategic Planning Documents: policies/oss-strategic-planning-documents.md
    - Complete Country Overview: policies/complete-country-overview.md
  - Contribution: contribution.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/EL-BID/OSS_policies