site_name: Open Source Policy Documentation
site_description: A comprehensive documentation site for public policies on open source software, organized by policy type.
site_url: https://EL-BID.github.io/OSS_policies
repo_url: https://github.com/EL-BID/OSS_policies
repo_name: EL-BID/OSS_policies 

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy

plugins:
  - search
  - i18n:
      docs_structure: folder
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: es
          name: Español
          build: true
          nav_translations:
            Home: Inicio
            Policies: Políticas
            Contribution: Contribución
          nav:
            - Inicio: index.md
            - Políticas:
              - Liberación Pública de Software Propiedad del Estado: policies/public-release-state-owned.md
              - Priorización de Código Abierto en Adquisiciones: policies/prioritize-open-source-procurement.md
              - Reutilización y Transferencia de Software Gubernamental: policies/reuse-transfer-government-software.md
              - Medidas de Seguridad para el Código Abierto: policies/open-source-security-measures.md
              - Plataformas para Compartir Código Abierto: policies/open-source-sharing-platforms.md
              - Contribución Obligatoria a Proyectos de Código Abierto: policies/mandatory-contribution-back-oss.md
              - Requisito de Estándares Abiertos: policies/open-standards-requirement.md
              - Marcos y Directrices de Licenciamiento: policies/licensing-frameworks-guidelines.md
              - Programas de Capacitación en Código Abierto: policies/oss-training-programs.md
              - Código Abierto en Documentos de Planificación Estratégica: policies/oss-strategic-planning-documents.md
              - Resumen Completo por País: policies/complete-country-overview.md
            - Contribución: contribution.md
        - locale: pt
          name: Português
          build: true
          nav_translations:
            Home: Início
            Policies: Políticas
            Contribution: Contribuição
          nav:
            - Início: index.md
            - Políticas:
              - Liberação Pública de Software de Propriedade do Estado: policies/public-release-state-owned.md
              - Priorização de Código Aberto em Aquisições: policies/prioritize-open-source-procurement.md
              - Reutilização e Transferência de Software Governamental: policies/reuse-transfer-government-software.md
              - Medidas de Segurança para Código Aberto: policies/open-source-security-measures.md
              - Plataformas para Compartilhamento de Código Aberto: policies/open-source-sharing-platforms.md
              - Contribuição Obrigatória de Volta para Projetos de Código Aberto: policies/mandatory-contribution-back-oss.md
              - Requisito de Padrões Abertos: policies/open-standards-requirement.md
              - Estruturas e Diretrizes de Licenciamento: policies/licensing-frameworks-guidelines.md
              - Programas de Capacitação em Código Aberto: policies/oss-training-programs.md
              - Código Aberto em Documentos de Planejamento Estratégico: policies/oss-strategic-planning-documents.md
              - Visão Geral Completa por País: policies/complete-country-overview.md
            - Contribuição: contribution.md

nav:
  - Home: index.md
  - Policies:
    - Public Release of State-Owned Software: policies/public-release-state-owned.md
    - Prioritize Open Source in Procurement: policies/prioritize-open-source-procurement.md
    - Reuse and Transfer of Government Software: policies/reuse-transfer-government-software.md
    - Open Source Security Measures: policies/open-source-security-measures.md
    - Open Source Sharing Platforms: policies/open-source-sharing-platforms.md
    - Mandatory Contribution Back to OSS: policies/mandatory-contribution-back-oss.md
    - Open Standards Requirement: policies/open-standards-requirement.md
    - Licensing Frameworks and Guidelines: policies/licensing-frameworks-guidelines.md
    - OSS Training Programs: policies/oss-training-programs.md
    - OSS in Strategic Planning Documents: policies/oss-strategic-planning-documents.md
    - Complete Country Overview: policies/complete-country-overview.md
  - Contribution: contribution.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/EL-BID/OSS_policies