sonar.projectKey=EL-BID_OSS_policies
sonar.projectName=OSS_policies

# Source code
sonar.sources=.

# Common exclusions
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/target/**,**/*.min.js,**/vendor/**,**/__pycache__/**,**/*.pyc,**/venv/**,**/.venv/**,**/coverage/**

# SCM
sonar.scm.provider=git