name: Feature Request
description: Suggest an improvement for the documentation site
labels: [enhancement]
body:
  - type: textarea
    id: feature
    attributes:
      label: Feature Description
      description: What would you like to see added or improved?
      placeholder: Describe your idea...

  - type: textarea
    id: problem
    attributes:
      label: Problem or Use Case
      description: What problem would this solve? How would it help users?
      placeholder: This would help by...

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How do you think this should work?
      placeholder: I think it should...

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Are there other ways to achieve this?

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information, mockups, or examples?
